const layoutOrder = [
    'menu',
    'darkModeSwitch',
    'simControlsLabel',
    'addEntities',
    'undo',
    'redo',
    'viz',
    'vizMini',
    'maps',
    'budget',
    'name',
    'resultsPhaseSelector',
    'saveConfigToLink',
    'saveConfigToShortLink',
    'saveConfigToText',
    'loadConfigText',
    'saveData',
    'svgSwitch',
    'showDownloadScreenLink',
]
export default layoutOrder
