const layoutOrder = [
    'menu',
    'darkModeSwitch',
    'simControlsLabel',
    'undo',
    'redo',
    'addVoter',
    'addCandidate',
    'addCandidateDistribution',
    'viz',
    'vizMini',
    'maps',
    'budget',
    'saveConfigToLink',
    'saveConfigToShortLink',
    'saveConfigToText',
    'loadConfigText',
    'svgMainDiv',
    'svgMiniDiv',
    'svgMaps',
    'svgBudget',
    'svgSwitch',
    'showDownloadScreenLink',
]
export default layoutOrder
