# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: VoteKit Demo
email: smartvotingsimulator1@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Here's a demo site that uses votekit. Votekit is an explorable sandbox that shows how different voting methods work. Single elections are presented visually using a spatial opinion model. Ensembles of elections are also presented with distributions of winning positions. (The rest of this description will become more accurate with time.) Some consideration of strategy is performed. Voting methods include single-winner systems like plurality, approval, condorcet methods, instant runoff, score, star, etc. Electoral methods also include proportional multi-member district methods like the Single Transferable Vote, Monroe, Thiele's Proportional Approval Voting, Phragmen's method, etc. Electoral methods also include party-list proportional methods like d'Hondt, Huntington-Hill, Webster, etc. Additional electoral methods include MMP and OLPR.
baseurl: "/votekit" # the subpath of your site, e.g. /blog
url: "https://paretoman.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: paretoman1
github_username: paretoman
author: Paretoman
minima:
  social_links:
    github: Paretoman
    twitter: Paretoman1
    youtube_channel: UCrwpT8YjxePjH0RxSCwbTlQ
    youtube_channel_name: Paretoman
thumbnail: "/src/VoteKit_Thumbnail.png"
production: true

# Build settings
theme: minima
plugins:
  - jekyll-relative-links
header_pages:
  - tutorial/index.md
  - s/index.md
  - index.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - package.json
